name: visual-ci-workflow

on: 
  push:
    branches:
    - 'main'

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        super_secret: ${{ secrets.PERCY_TOKEN }}
    - run: npm install
    - run: npm run cypress:run
